# SConscript
# vim: set ft=python:
#
# Eryn Wells <eryn@erynwells.me>

import os.path

Import('env')


subdirs = [
    # TODO: Put subdirectories here.
]

for d in subdirs:
    env.SConscript(os.path.join(d, 'SConscript'), {'env': env})


files = [
    # TODO: Put files here.
    'main.cc',
]

objs = []
for f in files:
    objs.append(env.Object(f))

# TODO: Add the library target for the package to test to LIBS.
test = env.Program('test', objs, LIBS=['gtest'])
Return('test')
