# SConscript
# vim: set ft=python:
# Eryn Wells <eryn@erynwells.me>

Library('gtest', [
    'gtest-all.cc',
    'gtest-death-test.cc',
    'gtest-filepath.cc',
    'gtest-port.cc',
    'gtest-printers.cc',
    'gtest-test-part.cc',
    'gtest-typed-test.cc',
    'gtest.cc',
    'gtest_main.cc'
])
